main:
  push:
    - services:
        - name: docker
          options:
            rootlessBuildkitd: 
              enabled: true
      stages:
        - name: Docker build and push
          script: |
            docker buildx build --no-cache \
              -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest \
              --platform=linux/amd64,linux/arm64/v8,linux/arm/v7,linux/386,linux/ppc64le,linux/s390x \
              . --push

$:
  vscode:
    - docker:
        image: docker.cnb.cool/ainb/images/default-dev-env
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -al
